accounts/urls.py
from django.urls import path

from .views import (RegisterView,
                    ProfileView,
                    CustomLoginView,
                    CustomLogoutView,
                    UserPasswordResetConfirmView,
                    UserPasswordResetDoneView,
                    UserPasswordResetCompleteView,
                    UserPasswordResetView,
                    UserPasswordChangeView,
                    UserPasswordChangeDoneView
                    )


# Create your tests here.

app_name = 'accounts'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('password_reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', UserPasswordChangeDoneView.as_view(), name='password_change_done'),

]

shopnest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:slug>/', views.HomeView.as_view(), name='category'),
    path('product/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('bucket/', views.BucketHome.as_view(), name='bucket-home'),
    path('bucket/status/<path:task_id>/', views.BucketResult.as_view(), name='bucket-result'),
    path('delete-object/<path:key>/', views.DeleteBucketObject.as_view(), name='delete-bucket-object'),
    path('download-bucket-object/<path:key>/', views.DownloadBucketObject.as_view(), name='download-bucket-object'),
    path('update-bucket-object/<path:key>/', views.UpdateBucketObject.as_view(), name='update-bucket-object'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils import timezone

from accounts.validators import phone_validator


# Create your models here.
class AccountManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, full_name, phone, password, **extra_fields):
        values = [email, full_name, phone]
        field_value_map = dict(zip(self.model.REQUIRED_FIELDS, values))
        for field_name, value in field_value_map.items():
            if not value:
                raise ValueError('The {} value must be set'.format(field_name))

        email = self.normalize_email(email)
        user = self.model(
            email=email,
            full_name=full_name,
            phone=phone,
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, full_name, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, full_name, phone, password, **extra_fields)

    def create_superuser(self, email, full_name, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, full_name, phone, password, **extra_fields)



class Account(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    full_name = models.CharField(max_length=150)
    phone = models.CharField(max_length=11, validators=[phone_validator], unique=True)
    date_of_birth = models.DateField(null=True, blank=True)
    picture = models.ImageField(null=True, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    last_login = models.DateTimeField(auto_now=True)

    objects = AccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name', 'phone']

    def get_full_name(self):
        return self.full_name

    def get_short_name(self):
        return self.full_name.split()[0]

    def __str__(self):
        return self.email

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth.forms import UserChangeForm as BaseUserChangeForm

from .models import Account

class RegistrationForm(UserCreationForm):
    date_of_birth = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        required=False
    )
    picture = forms.ImageField(required=False)

    class Meta:
        model = Account
        fields = [
            'email',
            'name',
            'phone',
            'date_of_birth',
            'picture',
            'password1',
            'password2'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'placeholder': f'Enter your {field.replace("_", " ")}'
            })
        self.fields['picture'].widget.attrs['class'] = 'form-control-file'

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if Account.objects.filter(email=email).exists():
            raise ValidationError('Email already registered')
        return email

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if len(phone) < 10:
            raise ValidationError('Phone number must be at least 10 digits')
        return phone


class AdminUserCreationForm(UserCreationForm):
    class Meta:
        model = Account
        fields = [
            'email',
            'name',
            'phone',
            'date_of_birth',
            'picture',
            'is_staff',
            'is_superuser'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['is_staff'].help_text = 'Access to the admin panel'
        self.fields['is_superuser'].help_text = 'Access to the admin panel without any permission'


class UserChangeForm(BaseUserChangeForm):
    password = ReadOnlyPasswordHashField(
        label="Password",
    )

    class Meta:
        model = Account
        fields = [
            'email',
            'name',
            'phone',
            'date_of_birth',
            'picture',
            'is_active',
            'is_staff',
            'is_superuser'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date_of_birth'].widget = forms.DateInput(attrs={'type': 'date'})


class ProfileForm(forms.ModelForm):
    date_of_birth = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        required=False
    )
    class Meta:
        model = Account
        fields = [
            'email',
            'name',
            'phone',
            'date_of_birth',
            'picture',
        ]
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['email'].disabled = True


class UserAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


class UserPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

accounts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.views import (PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView
                                       )


from accounts.forms import RegistrationForm, ProfileForm, UserAuthenticationForm, UserPasswordChangeForm
from accounts.models import Account


# Create your views here.

class RegisterView(CreateView):
    model = Account
    template_name = 'accounts/register.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('accounts:login')

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home')
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Successfully registered.')
        return response


class ProfileView(LoginRequiredMixin, UpdateView):
    model = Account
    form_class = ProfileForm
    template_name = 'accounts/profile.html'
    success_url = reverse_lazy('accounts:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request, 'Successfully updated.')
        return super().form_valid(form)


class CustomLoginView(LoginView):
    template_name = 'accounts/login.html'
    redirect_authenticated_user = True
    authentication_form = UserAuthenticationForm
    redirect_field_name = 'next'

    def get_success_url(self):
        user = self.request.user
        messages.success(self.request, f'Welcome Back {user.full_name}!')
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        return reverse_lazy('accounts:profile')


class CustomLogoutView(LogoutView):
    next_page = reverse_lazy('accounts:login')


class UserPasswordResetView(PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('accounts:password_reset_done')
    email_template_name = 'accounts/password_reset_email.html'


class UserPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'


class UserPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')


class UserPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'


class UserPasswordChangeView(PasswordChangeView):
    template_name = 'accounts/password_change.html'
    success_url = reverse_lazy('accounts:password_change_done')
    form_class = UserPasswordChangeForm


class UserPasswordChangeDoneView(PasswordChangeView):
    template_name = 'accounts/password_change_done.html'

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card shadow-sm border-0">
      <div class="card-header bg-dark text-white">
        <h4 class="mb-0">Login</h4>
      </div>
      <div class="card-body">
        <form method="post" novalidate>
          {% csrf_token %}

          {% for field in form %}
            <div class="mb-3">
              <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
              {{ field }}
              {% if field.errors %}
                <div class="text-danger small">
                  {% for error in field.errors %}
                    <div>{{ error }}</div>
                  {% endfor %}
                </div>
              {% endif %}
            </div>
          {% endfor %}

          {% if form.non_field_errors %}
            <div class="alert alert-danger">
              {{ form.non_field_errors }}
            </div>
          {% endif %}

          <div class="d-grid">
            <button type="submit" class="btn btn-dark">Login</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/password_change.html
{% extends 'base.html' %}
{% block title %}Change Password{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card shadow-sm border-0">
      <div class="card-header bg-dark text-white">
        <h4 class="mb-0">Change Password</h4>
      </div>
      <div class="card-body">
        <form method="post" novalidate>
          {% csrf_token %}
          {% for field in form %}
            <div class="mb-3">
              <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
              {{ field }}
              {% if field.errors %}
                <div class="text-danger small">
                  {% for error in field.errors %}
                    <div>{{ error }}</div>
                  {% endfor %}
                </div>
              {% endif %}
            </div>
          {% endfor %}
          <div class="d-grid">
            <button type="submit" class="btn btn-dark">Change Password</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends 'base.html' %}
{% block title %}Password Changed{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card shadow-sm border-0">
      <div class="card-header bg-dark text-white">
        <h4 class="mb-0">Password Changed</h4>
      </div>
      <div class="card-body text-center">
        <p>Your password has been successfully updated.</p>
        <a href="{% url 'accounts:profile' %}" class="btn btn-dark mt-3">Back to Profile</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}Password Changed{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card shadow-sm border-0">
      <div class="card-header bg-dark text-white">
        <h4 class="mb-0">Password Changed Successfully</h4>
      </div>
      <div class="card-body">
        <p class="mb-4">
          Your password has been changed. You may now log in with your new password.
        </p>
        <a href="{% url 'login' %}" class="btn btn-dark">Login to Your Account</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %}Set New Password{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card shadow-sm border-0">
      <div class="card-header bg-dark text-white">
        <h4 class="mb-0">Set New Password</h4>
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <div class="d-grid">
            <button type="submit" class="btn btn-dark">Save New Password</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% block title %}Email Sent{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card shadow-sm border-0">
      <div class="card-header bg-dark text-white">
        <h4 class="mb-0">Password Reset Email Sent</h4>
      </div>
      <div class="card-body">
        <p class="mb-4">
          If an account exists with this email, we've sent password reset instructions.
        </p>
        <a href="{% url 'login' %}" class="btn btn-dark">Return to Login</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}
{% block title %}Reset Password{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card shadow-sm border-0">
      <div class="card-header bg-dark text-white">
        <h4 class="mb-0">Reset Password</h4>
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <div class="d-grid">
            <button type="submit" class="btn btn-dark">Send Reset Link</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block title %}Your Profile{% endblock %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card shadow-sm border-0">
                <div class="card-header bg-dark text-white">
                    <h4 class="mb-0">Your Profile</h4>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data" novalidate>
                        {% csrf_token %}

                        {% for field in form %}
                            <div class="mb-3">
                                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                {{ field }}
                                {% if field.errors %}
                                    <div class="text-danger small">
                                        {% for error in field.errors %}
                                            <div>{{ error }}</div>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>
                        {% endfor %}

                        {% if user.picture %}
                            <div class="mb-3">
                                <p class="form-label">Current Picture:</p>
                                <img src="{{ user.picture.url }}" width="100" class="rounded border">
                            </div>
                        {% endif %}

                        <div class="d-grid">
                            <button type="submit" class="btn btn-dark">Update Profile</button>
                        </div>
                    </form>
                    <div class="text-center mt-3">
                        <a href="{% url 'accounts:password_change' %}" class="btn btn-outline-secondary btn-sm">
                            Change Password
                        </a>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-md-6">
    <div class="card shadow-sm border-0">
      <div class="card-header bg-dark text-white">
        <h4 class="mb-0">Create an Account</h4>
      </div>
      <div class="card-body">
        <form method="post" enctype="multipart/form-data" novalidate>
          {% csrf_token %}

          {% for field in form %}
            <div class="mb-3">
              <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
              {{ field }}
              {% if field.errors %}
                <div class="text-danger small">
                  {% for error in field.errors %}
                    <div>{{ error }}</div>
                  {% endfor %}
                </div>
              {% endif %}
            </div>
          {% endfor %}

          {% if form.non_field_errors %}
            <div class="alert alert-danger">
              {{ form.non_field_errors }}
            </div>
          {% endif %}

          <div class="d-grid">
            <button type="submit" class="btn btn-dark">Register</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}